package com.example.edu.seho.myhome.model

import android.os.Parcelable
import androidx.room.Entity
import androidx.room.PrimaryKey
import kotlinx.android.parcel.Parcelize

/** @author Sebastian Holm
 *  This data class is stored in the ShoppingCart database.
 *  @param id : is autogenerated to avoid clashes in the database.
 *  @param name : is supplied by the user and displayed in the shopping list fragment.
 *  @param done : is saving the state of the checkbox present in the shopping list fragment.
 */

@Parcelize
@Entity(tableName = "shoppingCart_table")
data class ShoppingCart (
    @PrimaryKey(autoGenerate = true)
    val id : Int,
    val name : String,
    var done : Boolean
) : Parcelable