package com.example.edu.seho.myhome.model

import android.os.Parcelable
import androidx.room.Entity
import androidx.room.PrimaryKey
import kotlinx.android.parcel.Parcelize

/** @author Sebastian Holm
 *  This data class is stored in the Storage database.
 *  @param id : is autogenerated to avoid clashes in the database.
 *  @param name : stores the name of the product
 *  @param category : stores the type or category of the product
 *  @param date : stores the best-by date of the product
 *  @param bought : stores the date which the product was bought.
 *  @param isUsed : indicates whether the item should be displayed.
 */

@Parcelize
@Entity(tableName = "storage_table")
data class Storage (
    @PrimaryKey(autoGenerate = true)
    val id : Int,
    val name : String,
    val category : String,
    val date : Int,
    val bought : Int,
    var isUsed : Boolean
    ) : Parcelable
